# 🧹 Data Cleaning & Preprocessing

## 📌 Objective

This notebook prepares the raw dataset for analysis by cleaning missing values, removing inconsistencies, and improving data quality.

---

---

## 📚 Libraries Used

- Pandas

---

In [114]:
import pandas as pd

---

## 📂 Tasks Performed

- Import dataset
- Create working copy
- Explore dataset
- Inspect data types
- Check missing values
- Handle null values
- Remove duplicate records
- Standardize text values
- Correct inconsistent entries
- Verify cleaned dataset
- Save cleaned dataset

---

# Import Dataset

In [115]:
original_df = pd.read_csv('orders_messy.csv')

df = original_df.copy()

# Dataset

In [116]:
df.head()

,order_id,user_id,age,city,order_time,day_type,cuisine,meal_type,restaurant_type,order_value,...,rating_given,is_repeat_order,mood,hunger_level,company,rainy_weather,Temperature,Humidity,Rain,Wind_Speed
0,1,2698,35,Pune,Evening,Weekend,Chinese,Dinner,Premium,971,...,1,Yes,Celebrating,NaN,Partner,No,23.4,94,0.1,19.5
1,2,3237,44,Mumbai,Night,Weekend,South Indian,Dinner,Budget,442,...,2,No,Lazy,Low,Family,No,26.6,92,0.2,18.7
2,3,3626,31,Delhi,Morning,Weekend,Biryani,NaN,Mid-range,739,...,2,Yes,Happy,Medium,Friends,No,28.9,86,0.0,8.3
3,4,3176,23,Delhi,Evening,Weekend,Biryani,Snacks,Mid-range,466,...,2,No,Happy,Medium,Alone,No,28.9,86,0.0,8.3
4,5,4824,26,Chandigarh,Morning,Weekday,Chinese,Lunch,Premium,927,...,2,No,Happy,Medium,Partner,Yes,27.6,86,0.0,9.2

# Information About Dataset

In [117]:
df.info()
# print(df.columns)

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             50000 non-null  int64
 1   user_id              50000 non-null  int64
 2   age                  50000 non-null  int64
 3   city                 47500 non-null  str
 4   order_time           47500 non-null  str
 5   day_type             47500 non-null  str
 6   cuisine              47500 non-null  str
 7   meal_type            47500 non-null  str
 8   restaurant_type      47500 non-null  str
 9   order_value          50000 non-null  int64
 10  discount_applied     47500 non-null  str
 11  delivery_fee         50000 non-null  int64
 12  time_taken_to_order  50000 non-null  int64
 13  rating_given         50000 non-null  int64
 14  is_repeat_order      47500 non-null  str
 15  mood                 47500 non-null  str
 16  hunger_level         47500 non-null  str
 17  company              47500 non-null  str
 18  rainy_weather        47500 non-null  str
 19  Temperature          50000 non-null  float64
 20  Humidity             50000 non-null  int64
 21  Rain                 50000 non-null  float64
 22  Wind_Speed           50000 non-null  float64
dtypes: float64(3), int64(8), str(12)
memory usage: 8.8 MB

In [118]:
df.describe()

,order_id,user_id,age,order_value,delivery_fee,time_taken_to_order,rating_given,Temperature,Humidity,Rain,Wind_Speed
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,23512.293120,3005.466160,30.975420,547.731100,59.642720,7.496720,2.994420,25.299370,89.007120,0.050480,20015.085228
std,16749.209428,1152.286323,7.804962,259.685968,23.043375,4.031059,1.413361,2.529528,3.787674,0.076662,139999.102187
min,-49941.000000,1000.000000,18.000000,100.000000,20.000000,1.000000,1.000000,22.000000,84.000000,0.000000,8.300000
25%,11332.750000,2013.000000,24.000000,323.000000,40.000000,4.000000,2.000000,23.300000,86.000000,0.000000,9.200000
50%,24220.000000,3004.000000,31.000000,547.000000,60.000000,7.000000,3.000000,26.600000,92.000000,0.000000,18.700000
75%,37143.250000,4002.000000,38.000000,772.000000,80.000000,11.000000,4.000000,27.600000,92.000000,0.100000,19.100000
max,50000.000000,4999.000000,44.000000,999.000000,99.000000,14.000000,5.000000,28.900000,94.000000,0.200000,999999.000000

# Missing Values

In [119]:
df[['city','order_time','day_type','cuisine','meal_type','restaurant_type','discount_applied',
   'is_repeat_order','mood','hunger_level','company','rainy_weather']] = df[['city','order_time','day_type','cuisine',
                                                                                             'meal_type','restaurant_type','discount_applied',
                                                                                            'is_repeat_order','mood','hunger_level','company','rainy_weather']].fillna('Unknown')

# Not Important Columns

In [120]:
df = df.drop(columns=['mood','hunger_level'])

In [121]:
df['order_id'] = df['order_id'].abs()

# Replace the column category

In [122]:
df['company'].value_counts()

company
Partner    12070
Friends    11925
Alone      11873
Family     11632
Unknown     2500
Name: count, dtype: int64

In [123]:
company_mapping = {
    'Partner': 'Zomato',
    'Friends': 'Swiggy',
    'Alone': 'Uber Eats',
    'Family': 'Domino\'s',
    'Unknown': 'Others'
}

df['company'] = df['company'].map(company_mapping)

In [124]:
df['company'].value_counts()

company
Zomato       12070
Swiggy       11925
Uber Eats    11873
Domino's     11632
Others        2500
Name: count, dtype: int64

#  Outlier Detection

In [125]:
df.boxplot(column='Wind_Speed')

In [126]:
df.sort_values("Wind_Speed", ascending=False).head(20)

,order_id,user_id,age,city,order_time,day_type,cuisine,meal_type,restaurant_type,order_value,...,delivery_fee,time_taken_to_order,rating_given,is_repeat_order,company,rainy_weather,Temperature,Humidity,Rain,Wind_Speed
16571,16572,2852,29,Delhi,Night,Weekday,Unknown,Lunch,Mid-range,638,...,96,2,2,No,Others,Yes,28.9,86,0.0,999999.0
33906,33907,1070,21,Bangalore,Night,Weekday,Unknown,Unknown,Budget,817,...,79,5,1,No,Others,No,22.0,84,0.0,999999.0
34234,34235,2840,25,Delhi,Night,Unknown,Unknown,Dinner,Budget,941,...,96,6,2,No,Others,Yes,28.9,86,0.0,999999.0
4532,4533,4756,19,Mumbai,Evening,Weekend,Unknown,Breakfast,Premium,397,...,40,10,4,Yes,Others,No,26.6,92,0.2,999999.0
16235,16236,3384,36,Bangalore,Evening,Weekday,Unknown,Dinner,Budget,473,...,57,7,2,Yes,Others,Yes,22.0,84,0.0,999999.0
9243,9244,3419,44,Hyderabad,Night,Weekend,Unknown,Unknown,Premium,269,...,84,8,4,No,Others,No,23.3,92,0.0,999999.0
15578,15579,2012,38,Mumbai,Afternoon,Weekend,Unknown,Breakfast,Premium,812,...,30,10,4,Yes,Others,No,26.6,92,0.2,999999.0
36417,36418,4197,40,Mumbai,Afternoon,Weekend,Unknown,Lunch,Unknown,875,...,44,12,3,Unknown,Others,No,26.6,92,0.2,999999.0
16573,16574,3129,23,Delhi,Night,Weekend,Unknown,Snacks,Budget,145,...,66,14,5,Yes,Others,No,28.9,86,0.0,999999.0
35500,35501,1095,43,Mumbai,Evening,Weekday,Unknown,Dinner,Mid-range,216,...,87,5,5,No,Others,Yes,26.6,92,0.2,999999.0
34585,34586,1899,34,Hyderabad,Morning,Weekend,Unknown,Dinner,Premium,181,...,34,4,2,No,Others,Yes,23.3,92,0.0,999999.0
32123,32124,2456,25,Hyderabad,Evening,Weekend,Unknown,Dinner,Mid-range,147,...,65,6,5,Yes,Others,No,23.3,92,0.0,999999.0
34278,34279,4927,37,Mumbai,Afternoon,Weekday,Unknown,Unknown,Mid-range,562,...,31,2,1,No,Others,No,26.6,92,0.2,999999.0
14925,14926,3288,35,Hyderabad,Afternoon,Weekend,Unknown,Snacks,Mid-range,501,...,51,4,5,No,Others,Yes,23.3,92,0.0,999999.0
27316,27317,1978,23,Pune,Unknown,Weekday,Unknown,Snacks,Budget,875,...,60,3,3,No,Others,No,23.4,94,0.1,999999.0
34924,34925,2009,33,Bangalore,Unknown,Weekday,Unknown,Dinner,Premium,281,...,61,10,3,No,Others,Yes,22.0,84,0.0,999999.0
35530,35531,1584,18,Bangalore,Night,Weekday,Unknown,Lunch,Mid-range,777,...,33,4,2,No,Others,No,22.0,84,0.0,999999.0
32100,32101,2581,40,Delhi,Evening,Unknown,Unknown,Lunch,Premium,394,...,70,2,5,No,Others,No,28.9,86,0.0,999999.0
3063,3064,3375,26,Chandigarh,Evening,Weekend,Unknown,Dinner,Premium,518,...,35,8,5,Yes,Others,No,27.6,86,0.0,999999.0
1768,1769,1426,30,Delhi,Night,Weekend,Unknown,Snacks,Unknown,818,...,27,13,2,Unknown,Others,No,28.9,86,0.0,999999.0

In [127]:
df['Wind_Speed'].value_counts()

Wind_Speed
18.7        8268
19.5        8200
19.1        8155
8.3         8151
9.2         8124
17.6        8102
999999.0    1000
Name: count, dtype: int64

In [128]:
median_value = df['Wind_Speed'].median()

df['Wind_Speed'] = df['Wind_Speed'].replace(999999.0, median_value)

In [129]:
df['Wind_Speed'].value_counts()

Wind_Speed
18.7    9268
19.5    8200
19.1    8155
8.3     8151
9.2     8124
17.6    8102
Name: count, dtype: int64

# Clean Dataset for Analysis

In [130]:
df.to_csv('clean.csv',index=False)

---

## 🔜 Next Step

The cleaned dataset is used in the **Analysis Notebook**.